include: package:flutter_lints/flutter.yaml

analyzer:

  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: true

  errors:
    deprecated_member_use_from_same_package: ignore
    missing_required_param: error
    missing_return: error

linter:

  rules:
    avoid_print: true
    prefer_single_quotes: false
    no_duplicate_case_values : true
    always_declare_return_types : true
    always_put_control_body_on_new_line : true
    always_specify_types : false
    always_put_required_named_parameters_first : false
    always_use_package_imports : true
    avoid_annotating_with_dynamic : false
    avoid_bool_literals_in_conditional_expressions : false
    avoid_catches_without_on_clauses : false
    avoid_classes_with_only_static_members : false
    avoid_empty_else : true
    avoid_equals_and_hash_code_on_mutable_classes : true
    avoid_escaping_inner_quotes : true
    avoid_field_initializers_in_const_classes : true
    avoid_init_to_null : false
    avoid_null_checks_in_equality_operators : false
    avoid_redundant_argument_values : true
    avoid_relative_lib_imports : true
    avoid_renaming_method_parameters : true
    avoid_return_types_on_setters : true
    avoid_returning_null_for_void : false
    avoid_setters_without_getters : true
    avoid_shadowing_type_parameters : true
    avoid_single_cascade_in_expression_statements : true
    avoid_slow_async_io : true
    avoid_type_to_string : true
    avoid_types_as_parameter_names : true
    avoid_void_async : true
    await_only_futures : true
    control_flow_in_finally : true
    directives_ordering : true
    empty_catches : false
    lines_longer_than_80_chars : false
    eol_at_end_of_file : false
    no_default_cases : false
    no_leading_underscores_for_local_identifiers : true
    no_logic_in_create_state : true
    null_check_on_nullable_type_parameter : false
    null_closures : false
    parameter_assignments : true
    prefer_const_constructors : true
    prefer_const_constructors_in_immutables : true
    prefer_const_declarations : true
    prefer_contains : true
    prefer_final_fields : true
    prefer_final_in_for_each : true
    prefer_final_locals : true
    prefer_final_parameters : false
    prefer_for_elements_to_map_fromIterable : true
    prefer_foreach : true
    prefer_function_declarations_over_variables : true
    prefer_generic_function_type_aliases : true
    prefer_if_elements_to_conditional_expressions : false
    prefer_int_literals : true
    prefer_interpolation_to_compose_strings : true
    prefer_is_empty : true
    prefer_is_not_operator : true
    prefer_iterable_whereType : true
    prefer_mixin : true
    prefer_null_aware_method_calls : false
    public_member_api_docs : false
    recursive_getters : true
    require_trailing_commas : false
    sized_box_for_whitespace : true
    sized_box_shrink_expand : true
    sort_child_properties_last : true
    sort_constructors_first : false
    sort_pub_dependencies : false
    sort_unnamed_constructors_first : true
    type_literal_in_constant_pattern : false
    test_types_in_equals : true
    throw_in_finally : true
    unawaited_futures : true
    unnecessary_await_in_return : true
    unnecessary_parenthesis : true
    unnecessary_this : true
    unnecessary_to_list_in_spreads : true
    unreachable_from_main : true
    use_function_type_syntax_for_parameters : true
    use_is_even_rather_than_modulo : true
    use_key_in_widget_constructors : true
    use_named_constants : true
    use_raw_strings : true
    use_rethrow_when_possible : true
    use_setters_to_change_properties : true
    valid_regexps : true