// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1hyoofGH5WLU3Ogc8khMxRW68jHTv2ng',
    appId: '1:1033271503159:web:580db838a9702d9b1fd2b2',
    messagingSenderId: '1033271503159',
    projectId: 'aadaiz-cadf7',
    authDomain: 'aadaiz-cadf7.firebaseapp.com',
    storageBucket: 'aadaiz-cadf7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7tnRrnZiiqeJHocRmdNPIFKAf1YWVtKM',
    appId: '1:1033271503159:android:55be9a548d924e331fd2b2',
    messagingSenderId: '1033271503159',
    projectId: 'aadaiz-cadf7',
    storageBucket: 'aadaiz-cadf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeudOTVe3vpCIjJwVZvkYnlVJZU8reXsY',
    appId: '1:1033271503159:ios:637c170a301d3c2a1fd2b2',
    messagingSenderId: '1033271503159',
    projectId: 'aadaiz-cadf7',
    storageBucket: 'aadaiz-cadf7.firebasestorage.app',
    iosBundleId: 'com.example.aadaizCustomerCrm',
  );
}
